version: '3.8'

services:
  db:
    image: postgres:latest
    restart: always
    expose:
      - 5432
    environment:
      POSTGRES_DB: casino_db
      POSTGRES_USER: casino_user
      POSTGRES_PASSWORD: casino_password
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build:
      context: ./api
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres+psycopg://casino_user:casino_password@db/casino_db
    ports:
      - "5000:5000"

  frontend:
    build:
      context: ./frontend
    restart: always
    ports:
      - "3000:3000"

volumes:
  postgres_data:
