version: '3.8'

services:
  reverse-proxy:
    image: traefik:v2.10
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - certificates:/certificates
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`localhost`)"
      - "traefik.http.routers.traefik.entrypoints=web"
      - "traefik.http.routers.traefik.middlewares=traefik-auth"
      - "traefik.http.routers.traefik-https.tls=true"
      - "traefik.http.routers.traefik-https.tls.certresolver=selfsigned"
    command:
      - "--providers.docker"
      - "--providers.docker.constraints=Label(`traefik.constraint-label`, `traefik-public`)"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.http.address=:80"
      - "--entrypoints.http.http.redirections.entryPoint.to=https"
      - "--entrypoints.http.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.http.http.redirections.entrypoint.permanent=true"
      - "--entrypoints.https.address=:443"
      - "--certificatesresolvers.selfsigned.acme.storage=/certificates/acme.json"
      - "--certificatesresolvers.selfsigned.acme.tlschallenge=true"
      - "--certificatesresolvers.selfsigned.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--api"
      - "--providers.http"
      - "--accesslog=true"
      - "--accesslog.filters.statuscodes=504"
  db:
    image: postgres:latest
    restart: always
    expose:
      - 5432
    environment:
      POSTGRES_DB: casino_db
      POSTGRES_USER: casino_user
      POSTGRES_PASSWORD: casino_password
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build:
      context: ./api
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres+psycopg://casino_user:casino_password@db/casino_db
    ports:
      - "5000:5000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.your-service-name.rule=Host(`localhost`)"
      - "traefik.http.routers.your-service-name.entrypoints=web"

  # frontend:
  #   build:
  #     context: ./frontend
  #   restart: always
  #   ports:
  #     - "3000:3000"

volumes:
  postgres_data:
  certificates:

